---
- name: Basic OS configuration on VMWARE
  hosts: vmware
  become: true
  become_user: root

  tasks:
    - name: Set up the vm hostname
      ansible.builtin.hostname:
        name: "{{ vm_hostname }}"
